---
title: "Las Reglas Básicas"
output: 
  github_document:
    pandoc_args: --webtex
---


## Algunas Propiedades Elementales

**1)** Si A es cualquier evento, entonces,  

* $P(A) \leq 1$  y  
* $P(A^c) = 1 − P(A)$


**2)** Complemento de conjunto vacio / Evento imposible  

* $P(\theta) = 0$

**3)** Si A y B son eventos tales que A ⊂ B entonces,

* P(B − A) = P(B) − P(A)

**4)** Si A y B son eventos tales que A ⊂ B, entonces,   

* P(A) ≤ P(B).

**5)** Propiedad de la aditividad finita: Sean $A_1$,..., $A_n$ n eventos mutuamente excluyentes, entonces,

* $P (\bigcup_{k=1}^n A_k) = \Sigma_{k=1}^n P(A_k)$.

De manera general, el método para asignar probabilidades a los eventos relativos a cualquier experimento aleatorio va de lo simple a lo complejo: primero se encuentra la probabilidad de una clase particular de eventos y, a partir de ahí, utilizando las propiedades de la función de probabilidad, se extiende ésta a una clase más amplia de eventos y después a familias cada vez más extensas.

**6)** Subaditividad finita o desigualdad de Boole, Sean $A_1$,... $A_n$ n eventos, entonces, 

* $P(\bigcup_{k=1}^n A_k) \leq \Sigma_{k=1}^n P(A_k)$

